### ISSUE TITLE
include e.toString in error messages

### ISSUE THREAD

**Issue by marchage** [leftstick/vscode-esformatter#7]
Hi,

I just spend some time trying to figure out why esformatter was running as an npm script but not with your extension: 

>Formating failed, your code is invalid JavaScript

Added a `e.toString()` to line 84 in src/server/index.ts and got:

> Error: Plugin 'esformatter-rename' is not supported. Please consider opening an issue for supporting

which help. Perhaps ~you should add~ it should be added.

All the best,

Marc

ps close at your discretion

**Comment by leftstick** [comment]
Thanks for reporting the issue, the message `Error: Plugin 'esformatter-rename' is not supported. Please consider opening an issue for supporting` should be in the notification instead of `Formating failed, your code is invalid JavaScript`, it used to be. No idea why this feature broke now.

I just fixed this notification issue, and support the plugin `esformatter-rename`, you can try it now with `1.6.0`

**Comment by marchage** [comment]
I had forgotten about the extension that really worked for me. But I was able to find it by issue, (and the fact that my activities are not many haha, so "2018" was enough). I'll give it a try. Best wishes.
